version: '3'

services:
  frontend:
    image: sridharbr28/mern-frontend
    container_name: frontend-container
    ports:
      - "3000:80"

  backend:
    image: sridharbr28/mern-backend
    container_name: backend-container
    ports:
      - "5000:5000"

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
