version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo-container

  backend:
    image: sridharbr28/mern-backend
    container_name: backend-container
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    image: sridharbr28/mern-frontend
    container_name: frontend-container
    depends_on:
      - backend
    ports:
      - "3000:80"
